### ISSUE TITLE
500:Internal Server Error

### ISSUE THREAD

**Issue by arronqing** [happydasch/btplotting#50] opened 2023-05-04 04:17 UTC
When using btplotting for online data visualization, a 500: Internal Server Error error is reported, and the error code is as follows:

HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Python\python3.8.9\lib\site-packages\tornado\web.py", line 1786, in _execute
    result = await result
  File "C:\Python\python3.8.9\lib\site-packages\bokeh-3.2.0.dev1-py3.8.egg\bokeh\server\views\doc_handler.py", line 54, in get
    session = await self.get_session()
  File "C:\Python\python3.8.9\lib\site-packages\bokeh-3.2.0.dev1-py3.8.egg\bokeh\server\views\session_handler.py", line 145, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "C:\Python\python3.8.9\lib\site-packages\bokeh-3.2.0.dev1-py3.8.egg\bokeh\server\contexts.py", line 242, in create_session_if_needed
    self._application.initialize_document(doc)
  File "C:\Python\python3.8.9\lib\site-packages\bokeh-3.2.0.dev1-py3.8.egg\bokeh\application\application.py", line 192, in initialize_document
    h.modify_document(doc)
  File "C:\Python\python3.8.9\lib\site-packages\bokeh-3.2.0.dev1-py3.8.egg\bokeh\application\handlers\function.py", line 142, in modify_document
    self._func(doc)
  File "C:\Python\python3.8.9\lib\site-packages\btplotting-0.2.1-py3.8.egg\btplotting\webapp.py", line 54, in make_document
    model = self._model_factory_fnc(doc)
  File "C:\Python\python3.8.9\lib\site-packages\btplotting-0.2.1-py3.8.egg\btplotting\analyzers\plot.py", line 64, in _app_cb_build_root_model
    client = LiveClient(doc,
  File "C:\Python\python3.8.9\lib\site-packages\btplotting-0.2.1-py3.8.egg\btplotting\live\client.py", line 55, in __init__
    self.model, self._refresh_fnc = self._createmodel()
  File "C:\Python\python3.8.9\lib\site-packages\btplotting-0.2.1-py3.8.egg\btplotting\live\client.py", line 177, in _createmodel
    tabs = Tabs(
  File "C:\Python\python3.8.9\lib\site-packages\bokeh-3.2.0.dev1-py3.8.egg\bokeh\model\model.py", line 97, in __new__
    raise ValueError("'id' cannot be used together with property initializers")
ValueError: 'id' cannot be used together with property initializers

Tried python 3.8.9, 3.8.6, but it didn't work
Use btplotting version 0.2.1

**Comment by zgpnuaa** [comment] 2023-06-29 13:40
Did you find the cause of the problem when trading in live mode? @arronqing

**Comment by happydasch** [comment] 2023-06-30 04:13
Will close this in favor of #46

**Closed** 2023-06-30 04:13 UTC
